-- AlterTable
ALTER TABLE `CommonData` MODIFY `status` ENUM('ASSIGN', 'PENDING', 'REJECTED', 'ONGOING', 'CANNOTVERIFY', 'REFER', 'POSITIVE', 'NEGATIVE', 'REASSIGN', 'REVIEW', 'REWORK') NOT NULL;

-- AlterTable
ALTER TABLE `Verification` MODIFY `status` ENUM('ASSIGN', 'PENDING', 'REJECTED', 'ONGOING', 'CANNOTVERIFY', 'REFER', 'POSITIVE', 'NEGATIVE', 'REASSIGN', 'REVIEW', 'REWORK') NOT NULL;
